### ISSUE TITLE
Stoplight urls in docs instead of api path

### ISSUE THREAD

**Issue by steve-ross** [bigcommerce/api-specs#1018]
Looks like there is an issue with the generated URLs as they should be (for example) `/api/storefront/cart-summary/` or `/remote/v1/cart/add`

See screenshot: 
![image](https://user-images.githubusercontent.com/297351/196738890-ec0b4e50-5a0c-49d5-a303-9542aa060d63.png)

**Comment by slsriehl** [comment]
Thanks for reporting, @steve-ross. We're opening a ticket with our docs SaaS to dig further into this issue.

**Comment by slsriehl** [comment]
Thanks again for this, @steve-ross. We resolved this issue and subsequently migrated to another docs platform.
