### ISSUE TITLE
Create a Variant Image Documentation Update

### ISSUE THREAD

**Issue by atensoftware** [bigcommerce/api-specs#1035]
Currently, the documentation for Creates a Variant Image located at:
https://developer.bigcommerce.com/api-reference/45bef4d261b13-create-a-variant-image
states "Creates a Variant Image"
Instead, it should say "Creates a new Variant Image if none is assigned, or replaces the existing Variant image if one is already assigned.  There is no way to delete a variant image via the API."

I tested the above using Postman to confirm.

**Comment by slsriehl** [comment]
Created [DEVDOCS-5099]

**Comment by slsriehl** [comment]
Thanks for making our docs better, @atensoftware!
