### ISSUE TITLE
Create a Product is partially documented

### ISSUE THREAD

**Issue by armpogart** [bigcommerce/api-specs#1073]
It is possible currently to create multiple variants with initial product creation request, but that is not documented in the spec and on the website, though it was documented on the website previously.

**Comment by slsriehl** [comment]
Hi @armpogart -- sorry for the delay in responding.

You're right, this could be clearer. I've added some notes in the endpoint description. Currently, the schema for the `variants` array is at the bottom of the POST object body, but this may not have been the case when you posted this issue.

Thank you for opening this issue and building with BigCommerce. If you want to open more issues in the future, head over to our new consolidated repo at [bigcommerce/docs](https://github.com/bigcommerce/docs/issues).
