### ISSUE TITLE
Add endpoint "/catalog/shared-product-options"

### ISSUE THREAD

**Issue by stephancasas** [bigcommerce/api-specs#1102]
Documentation for the `/catalog/shared-product-options` endpoint does not appear to be published in the current version of the API reference.

**Comment by slsriehl** [comment]
Hi @stephancasas. This endpoint is in closed beta and will not be in published documentation until such time as it's generally available. We make no guarantees that it will continue to work as it has in the past. 

If you're interested in participating in the closed beta, the first step is to join our developer community. Once you're added to the Slack, you can DM me for more information. Learn more at [developer.bigcommerce.com/community](developer.bigcommerce.com/community).

cc @bc-hnbarr
