### ISSUE TITLE
Support for code generation

### ISSUE THREAD

**Issue by petedoyle** [bigcommerce/api-specs#1143]
A question more than anything. :) Thanks for listening. 

I know this repo is about generating docs, but I'd also love to generate models/clients. For the past couple of years it's been pretty common for the specs to have (sometimes small) validation errors when using the official [OpenAPI generator](https://openapi-generator.tech/). 

Any thoughts on extending the scope of this project to also be useful for generating models/clients? Ideally, it'd be amazing to validate in CI during PRs, such that the specs on the default branch (currently `master`) always validate and succeed in generating code. 

As a customer of the BigCommerce API, my ideal usage is to 1) read the docs enough to understand the big picture of how the API works, then 2) generate all the code needed to interact with the API. This is _much_ easier than having to read the docs in great enough detail to write my own client.

Thanks for the work you all do to keep these docs up to date! :)

**Comment by kzhang-dsg** [comment]
See my patched repo for code generation: https://github.com/kzhang-dsg/bigcommerce-api-specs/

I use my patched repo to generate models in my typescript bigcommerce-api-client project: https://github.com/kzhang-dsg/bigcommerce-api-client

I also raised several PRs from my patched repo, but those changes haven't got merged yet:
https://github.com/bigcommerce/api-specs/pull/1210
https://github.com/bigcommerce/api-specs/pull/1211
https://github.com/bigcommerce/api-specs/pull/1214
https://github.com/bigcommerce/api-specs/pull/1233
https://github.com/bigcommerce/api-specs/pull/1241
https://github.com/bigcommerce/api-specs/pull/1249

**Comment by slsriehl** [comment]
@petedoyle @kzhang-dsg and @bobbyshaw -- see the excellent work @bobbyshaw has done to standardize operationIds over at [bigcommerce/docs 45](https://github.com/bigcommerce/docs/pull/45). I'm hoping to get it merged up this coming week, with tags pushed so people using more manually created clients can find the last "good" commit for their codebase.

I'm going to close this out and mention it in PR 45 so you can more conveniently check the status. You can open new issues over at [bigcommerce/docs](https://github.com/bigcommerce/docs/issues). 

Thanks for building with BigCommerce and contributing to the quality of our DX!
