### ISSUE TITLE
Incorrect endpoint URL for Current Customer API

### ISSUE THREAD

**Issue by CNanninga** [bigcommerce/api-specs#1167]
The API reference for Current Customer API incorrectly documents the endpoint as /api/storefront
/customer/current.jwt.  It should be /customer/current.jwt.

**Comment by CNanninga** [comment]
Should have included the link: https://developer.bigcommerce.com/api-reference/766da87d99a41-get-current-customer

**Comment by slsriehl** [comment]
Thanks again for pointing this out, @CNanninga! Much appreciated. This looks to indeed be fixed. Please reopen if needed.
