### ISSUE TITLE
Array vs Objects

### ISSUE THREAD

**Issue by pmathbliss** [bigcommerce/api-specs#1178]
https://github.com/bigcommerce/api-specs/edit/master/reference/catalog.v3.yml

Can you please fix all the places where the returning value is either an array or an object? If there is one value in the list can it be and array with that one value.

The example on this page has one error in the response with [] but when testing on a site once error on the response gives me an object.

Its not the only place where this happens and it breaks many json seriallizers. The product custom url is also broken.

Documentation:
```
"errors": [
    {
      "status": 0,
      "title": "string",
      "type": "string",
      "errors": {
        "property1": "string",
        "property2": "string"
      }
    }
  ],
```
Example Response:
```
"errors":
{
"status":422,"title":"Please verify if all required fields are present in the request body and are filled with values correctly.","type":"https://developer.bigcommerce.com/api-docs/getting-started/api-status-codes",
"errors":{"0.name":"A duplicate category with the name: 'SQUARE TOE' was found in the same parent"
}
}
```

**Comment by slsriehl** [comment]
Hi @pmathbliss. Thanks for opening this issue. This particular one is part of a set of changes we plan to release soon. 

I'll keep this issue open until we confirm that the deployment does show this fix.

**Comment by slsriehl** [comment]
These appear to be resolved - we did a lot of work on error objects when we moved to the new Dev Center in March 2023. Apologies for taking so long to close this issue out. If you have more issues to raise, head over to [bigcommerce/docs](https://github.com/bigcommerce/docs). We look forward to seeing you there!
