### ISSUE TITLE
[Feature Request] A way to fetch variant metafields in batch

### ISSUE THREAD

**Issue by guiquintelas** [bigcommerce/api-specs#1279]
Hey BigCommerce team!

Not sure this if is the right place to request api features. Feel free to redirect me to the appropriate place if needed.

I'm currently developing a BigCommerce app that needs to fetch all variants' metafields from the whole catalog. I was expecting to be able to `include` them on a product/variant request, but by the looks of it, it's not supported. Then I started looking for a direct metafield endpoint, I can see that a metafield contains a `resource_type` and `resource_id` fields, so I imagine they are stored on a different _table_. But no luck with that either 😞 

So, with that said, I guess I need to request this feature to be implemented. Either of the above solutions would do the trick. I can also imagine that this definitely can be useful for many other developers, as this is a developer-specific field.

Thanks in advance!

**Comment by slsriehl** [comment]
Hi @guiquintelas! Apologies for the delay in response.

Dedicated metafield endpoints are on our roadmap, but I don't have a timeline for you on that. To stay in the loop on the most current releases and beta participation opportunities, you can join our developer community. Learn more at [developer.bigcommerce.com/community](https://github.com/bigcommerce/api-specs/issues/developer.bigcommerce.com/community).

If you have further issues to raise, head over to [bigcommerce/docs](https://github.com/bigcommerce/docs), our new consolidated repo for docs and API reference.

Thank you for raising this issue; questions like yours help make our product and our docs better for everyone.
