### ISSUE TITLE
StoreInformation.logo is an array not an object

### ISSUE THREAD

**Issue by kellpossible** [bigcommerce/api-specs#1358]
StoreInformation.logo is an object in the spec, but I'm getting an empty array returned, which is breaking searialization.

**Comment by slsriehl** [comment]
I added an anyOf that should help not break serialization; see [bigcommerce/docs PR 38](https://github.com/bigcommerce/docs/pull/38). If you have further issues to raise, head over to [bigcommerce/docs](https://github.com/bigcommerce/docs), our new consolidated repo for docs and API reference.
