### ISSUE TITLE
Webhook id should be integer not number?

### ISSUE THREAD

**Issue by kellpossible** [bigcommerce/api-specs#1376]
https://github.com/bigcommerce/api-specs/blob/main/reference/webhooks.v3.yml#L594 It seems like the webhook id, and probably the timestamps should be integers, not numbers?

**Comment by slsriehl** [comment]
Agree, @kellpossible, that's much more descriptive. I've updated the spec in [bigcommerce/docs PR 39](https://github.com/bigcommerce/docs/pull/39). 

If you have further issues to raise, head over to [bigcommerce/docs](https://github.com/bigcommerce/docs), our new consolidated repo for docs and API reference.

Many thanks for raising these issues and we hope to hear from you over there.
