### ISSUE TITLE
Get all products variant id missing

### ISSUE THREAD

**Issue by kellpossible** [bigcommerce/api-specs#1460]
In get all products, the variant id is missing

image_url looks like it might also be missing

**Comment by slsriehl** [comment]
Hi @kellpossible! Apologies again for the late responses.

`Get all products` gets all `base variants`. For example, in my store I have 15 products, which is 15 base variants. To get variants, which may be more representative of saleable items, you can either `?include=variants` or use the [Get all variants (batch)](/docs/rest-catalog/product-variants/variants-batch#get-all-variants) endpoint. 

When I include variants in the `Get all products` call, each of my 15 products includes a `variants` array. When I use the `Get all variants` batch endpoint, I get the 41 variants on my store. In both of these instances, the variant object includes an `id` and an `image_url`. It sounds like for your use case, one of these strategies might be what you're looking for.

I'm going to close this issue as resolved, as there isn't a variant_id or image_url property on `Get all products`. If you have more to add or offer, open a new issue over at [bigcommerce/docs](https://github.com/bigcommerce/docs/issues). Thanks for building with BigCommerce.
