### ISSUE TITLE
Incorrect guidance on product option value endpoint

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/api-specs#1468]
https://developer.bigcommerce.com/docs/rest-catalog/product-variant-options/values#update-a-product-variant-option-value

`is_default` is documented with the note:

> The flag for preselecting a value as the default on the storefront. This field is not supported for swatch options/modifiers.

I have been able to the swatch option value with the `is_default` in BC admin and via the API without issue. Does this annotation need removing or correcting?

![Screenshot 2023-09-14 at 10 09 13](https://github.com/bigcommerce/api-specs/assets/553566/ae77800f-4b8e-405d-a7a9-aa490327eb90)
![Screenshot 2023-09-14 at 10 09 20](https://github.com/bigcommerce/api-specs/assets/553566/92a12d0f-8468-4f00-8542-614f3a497e3f)

**Comment by slsriehl** [comment]
@bobbyshaw -- I've opened a PR and I'm waiting for the product team's review, as this guidance is repeated many times across the catalog docs. I'm going to close this issue and let the PR take precedence.
