### ISSUE TITLE
Inventory API model

### ISSUE THREAD

**Issue by Charlieface** [bigcommerce/api-specs#1509]
The model for the Inventory API seems to be missing.

https://developer.bigcommerce.com/docs/rest-management/inventory

I would have expected a YML under https://github.com/bigcommerce/api-specs/tree/main/reference

Could this be added?

**Comment by slsriehl** [comment]
@Charlieface we're in the middle of consolidating docs from multiple sources into a new repo, as I see you're aware from your issue over in bigcommerce/docs :)

The next phase of the project includes making the Inventory API specs available.

I am going to close this issue, but you are very welcome to reopen over in bigcommerce/docs and we'll keep it open until the Inventory specs are up.

Thanks for raising the issue and building with BC!
