### ISSUE TITLE
Official support

### ISSUE THREAD

**Issue by stevenbrookes** [bigcommerce/api-specs#246]
Hi

We are about to add support for BugCommerce to our SaaS solution.  I'm very glad to see this set of OpenAPI specs as it will make that process much easier.  A couple of questions/observations.

1.  Are these specs officially supported by BigCommerce?  They seem actively maintained, but I didn't see any reference to them in the BC documentation?
2. I've only looked at the CatalogV3 API so far, but I notice that swagger.io and spotlight show there are a few errors in the files.  Similarly generating client libraries from the spec, throws some errors too.  Are you aware of this, or shall I post up some more specific issues?
3. An observation.  You've specified that Accept and Content-Type are required headers on most if not all the API endpoints.  Whilst this may be technically correct, the impact is that the client library generators such as openapi generator, require these two parameters to be sent into every API call.  It's usually very straightforward to get HTTP client to send in default headers like this without having to pass them via the generated API stub functions.  Would you consider removing them from the specs?  

Regards

Steven Brookes
TideConnects.com

**Comment by stevenbrookes** [comment]
@ektravel could you comment on the above question?  Thanks

**Comment by ektravel** [comment]
@stevenbrookes Thank you for sharing your feedback. We will review your questions and get back to you shortly.

**Comment by uwikaiddi** [comment]
Hi @stevenbrookes! 
Thanks so much for your questions. I'll answer them as best I can.

1. Yes, these spec files are officially supported by BigCommerce.
2. We are aware of some of the errors in the files. We're working to resolve these.
3. I recommend posing this question in the [BugCommerce Developer Community](https://support.bigcommerce.com/s/group/0F913000000HLjECAW/bigcommerce-developers). Suggestions for these types of requests are a great way to bring attention and start a conversation.

Thanks again!
