### ISSUE TITLE
Catalog V3 spec issues

### ISSUE THREAD

**Issue by stevenbrookes** [bigcommerce/api-specs#327]
Hi 

We saw a couple of issues in the V3 catalog specification whcih gave incorrect code generation.

1.  Additional  type: string on line 18199 productVariant_Full

2. On line 19182 product_Post
            $ref: '#/definitions/productVariant_Post_Product'
 should be 
            type: array
            items:
              $ref: '#/definitions/productVariant_Post_Product'

3.  On line 20026 product_Full
                   $ref: '#/definitions/productVariant_Full'
should be
            type: array
            items:
              $ref: '#/definitions/productVariant_Full'

Regards

Steve

**Comment by stevenbrookes** [comment]
Hi

Another one for you the update product endpoint should take an array of productVariant_Put_Product, not just the object.

  product_Put:
    description: The model for a PUT to update a product.
    allOf:
      - type: object
        properties:
          id:
            type: integer
            description: |
              The unique numerical ID of the product; increments sequentially.
            x-required:
              - put
      - $ref: '#/definitions/product_Base'
      - type: object
        properties:
          variants:
            type: array
            items:
              $ref: '#/definitions/productVariant_Put_Product'


Is there much point me posting these fixes for you?

Regards

Steve

**Comment by stevenbrookes** [comment]
Next one

Putting                   allOf:  when you only have one object is unnecessary and does cause issues with some client library builder.

Example

Around line 2187

     responses:
        '200':
          description: ''
          schema:
            type: object
            title: Variant Collection Response
            properties:
              data:
                type: array
                items:
                  allOf:
                    - $ref: '#/definitions/productVariant_Full'
              meta:
                $ref: '#/definitions/metaCollection_Full'

The allOf is unnecessary.

**Comment by ektravel** [comment]
@stevenbrookes Thank you for bringing this to our attention.

**Comment by traci707** [comment]
> Hi @stevenbrookes 

Thank you for bringing this information to our attention. I have been able to find every item on your list except for the first one. Is there a variable that should be also of string type? I am not understanding the first one.
> 
> 1. Additional  type: string on line 18199 productVariant_Full

**Comment by stevenbrookes** [comment]
Hi Traci

Regarding   1.	Additional type: string on line 18199 productVariant_Full

I can see that issue has already been fixed, so you can ignore that one now.

**Comment by uwikaiddi** [comment]
Hi @stevenbrookes,
This issue has been converted into an internal JIRA ticket. 
We'll reference this issue in the PR that fixes the remaining issues.

Thanks again for bringing this to our attention!

**Comment by traci707** [comment]
Hi @stevenbrookes ,
I am working on this ticket. Sorry for the delay. The Catalog swagger file is very large and it causes the editor to crash. I hope to have the file up to date and corrected next week.

**Comment by ektravel** [comment]
Updated `product_Full` model on[ PR 429](https://github.com/bigcommerce/api-specs/pull/429).
Removed `allOf` keyword from `productVariant_Put` and `productVariant_Post` on [PR 439](https://github.com/bigcommerce/api-specs/pull/439).

**Comment by traci707** [comment]
@stevenbrookes The changes requested have been implemented, sorry for the delay. If you have further questions/issues please let us know.
