### ISSUE TITLE
API /orders/payment_actions/refunds of orders.v3.yml in incorrect format

### ISSUE THREAD

**Issue by dleguellecfortuitas** [bigcommerce/api-specs#362]
NSwag studio gives the following error when attempting to create a C# client.

_Newtonsoft.Json.JsonReaderException: Invalid property identifier character: ?. Path 'paths['/orders/payment_actions/refunds'].post.responses.503.examples', line 1, position 18036._

Also, upon inspecting the BigCommerce API docs https://developer.bigcommerce.com/api-reference/store-management/order-transactions/payment-actions/getorderrefunds the responses other than 200 do not show.

**Comment by uwikaiddi** [comment]
Hi @dleguellecfortuitas,
Thanks for bringing this to our attention. I've created an internal ticket to address this. 
We'll link to the associated PR when it is created. 
Thanks for your patience!

**Comment by ektravel** [comment]
@dleguellecfortuitas The syntax issue you reported appears to be specific to Nswag Studio. I was not able to replicate this error using our API design management tool. 
Please refer to the [Create a Refund](https://developer.bigcommerce.com/api-reference/store-management/order-transactions/payment-actions/postrefund) endpoint for the 503 error schema and example.
`POST  /orders/{order_id}/payment_actions/refunds`
