### ISSUE TITLE
Update Product Sort Order Response Incorrect Format

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/api-specs#452]
The documented response format is an array with keys `data` and `meta` like other `v3` endpoints. 

However,  it actually returns an array of productSortOrders. I'm not sure if the endpoint should be updated to be more consistent with other endpoints but in the meantime, it would be good to get the documentation updated.

Thanks.

![Screenshot 2021-08-12 at 11 26 01](https://user-images.githubusercontent.com/553566/129182184-df592e68-588b-4522-820f-fe489ff68450.png)
![Screenshot 2021-08-12 at 11 29 26](https://user-images.githubusercontent.com/553566/129182192-c508250e-580b-47f3-bb05-4de6b90e197c.png)

**Comment by uwikaiddi** [comment]
Hi @bobbyshaw, thanks for pointing this out!
 
I've created an internal ticket to investigate this.
You'll be alerted to the resolution.

**Comment by ektravel** [comment]
Thank you for bringing this to our attention. I've submitted a fix on [PR 470](https://github.com/bigcommerce/api-specs/pull/470).
