### ISSUE TITLE
catalog.v3.yml won't import into Postman

### ISSUE THREAD

**Issue by drahija-gli** [bigcommerce/api-specs#473]
When I try and import the catalog.v3.yml file into Postman it's throwing an error "Error while importing: format not recognized"

I've been trying to track down what the problem might be, but so far haven't been able to uncover anything.

**Comment by uwikaiddi** [comment]
Hi @drahija-gli, thank you for pointing this out.
Due to the tool we use to generate our external-facing documentation, not all of our API spec file formatting is readily compatible with Postman. We're looking into finding an alternative solution next year.
