### ISSUE TITLE
catalog.v3.yml

### ISSUE THREAD

**Issue by dleguellecfortuitas** [bigcommerce/api-specs#474]
The specs have multiple structural violations.  Code gen tools like NSwagStudio cannot parse the definition properly.
![BCCatalogV3ParseErrors](https://user-images.githubusercontent.com/38509772/130869976-06b8dd9e-2807-4894-9b36-ecaaa6950c2d.PNG)

**Comment by uwikaiddi** [comment]
Hi @dleguellecfortuitas, thank you for pointing this out.
Due to the tool we use to generate our external-facing documentation, not all of our API spec file formatting is readily compatible with Postman. We're looking into finding an alternative solution next year.
