### ISSUE TITLE
Management API - v2 order schema for Multi-Currency-enabled stores

### ISSUE THREAD

**Issue by martin-hudak** [bigcommerce/api-specs#542]
Hi everybody and thank you for your work :)

I've noticed that in management API v2/orders there are optional order fields that are present when the store has multiple currencies:

> The following additional fields are returned on orders when Multi-Currency is enabled on the store:
> store_default_currency_code - the currency code of the store’s default currency.
> store_default_to_transactional_exchange_rate - the exchange rate between the store’s default currency and the transactional currency used in the order.
> 

(https://developer.bigcommerce.com/api-reference/store-management/orders)

In orders.v2.oas2.yml these fields are present in response example, but not in the `#/components/schemas/order_Resp`.
Is there some technical problem or it just was forgotten?

Thank you,
Martin

**Comment by slsriehl** [comment]
Many thanks, @martin-hudak .  I've opened a ticket for us to look into this.

**Comment by slsriehl** [comment]
Closing this out. See changes in the following:
* #644 

Please open another issue if something else comes up. Thanks for participating!
