### ISSUE TITLE
Storefront Cart API - Create Cart missing schema details for optionSelections

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/api-specs#95]
Hi there,

I believe `optionSelections` should be detailed in the schema for the [Create Cart endpoint](https://developer.bigcommerce.com/api-reference/storefront/carts/cart/createacart) of Storefront Cart API.

This is detailed within the Management APIs but seems to have been omitted on Storefront API, there might be a good reason that I am missing (?), but I've opened the issue and will open a pull request for this too. 

Hopefully it helps!

**Comment by aglensmith** [comment]
Thanks again for the PR.
