### ISSUE TITLE
Undocumented functionality on Get All Brands

### ISSUE THREAD

**Issue by bobbyshaw** [bigcommerce/api-specs#950]
From my testing of the [get all brands endpoint](https://developer.bigcommerce.com/api-reference/c2610608c20c8-get-all-brands), there is more functionality than documented. 

You can sort results using the `sort` param, e.g. `sort=name`. 

You can search by partial name, e.g. `name:like=Foo`

**Comment by slsriehl** [comment]
Thanks @bobbyshaw. This still appears undocumented. I've opened [DEVDOCS-5098].

**Comment by slsriehl** [comment]
Thanks, @bobbyshaw! This was updated in the following PR:
* #1360
